package org.vetcontrol.model;
// Generated Dec 17, 2009 1:05:58 PM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Countrybook generated by hbm2java
 */
@Entity
@Table(name = "countrybook", catalog = "project1")
public class CountryBook implements java.io.Serializable {

    private Integer id;
    private String code;
    private Set<CultureString> names = new HashSet<CultureString>();

    public CountryBook() {
    }

    public CountryBook(String code) {
        this.code = code;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "code", nullable = false, length = 2)
    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    @OneToMany
    @JoinColumn(name = "id")
    public Set<CultureString> getNames() {
        return this.names;
    }

    public void setNames(Set<CultureString> names) {
        this.names = names;
    }

    public void addName(CultureString name){
        names.add(name);
    }
}


