package org.vetcontrol.information.model;
// Generated Dec 18, 2009 2:51:50 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * StringCultureId generated by hbm2java
 */
@Embeddable
public class StringCultureId implements java.io.Serializable {

    private long id;
    private String locale;

    public StringCultureId() {
    }

    public StringCultureId(String locale) {
        this.locale = locale;
    }

    @Column(name = "id", nullable = false)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Column(name = "locale", nullable = false, length = 2)
    public String getLocale() {
        return this.locale;
    }

    public void setLocale(String locale) {
        this.locale = locale;
    }

    @Override
    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof StringCultureId)) {
            return false;
        }
        StringCultureId castOther = (StringCultureId) other;

        return (this.getId() == castOther.getId())
                && ((this.getLocale() == castOther.getLocale()) || (this.getLocale() != null && castOther.getLocale() != null && this.getLocale().equals(castOther.getLocale())));
    }

    @Override
    public int hashCode() {
        long result = 17;

        result = 37 * result + this.getId();
        result = 37 * result + (getLocale() == null ? 0 : this.getLocale().hashCode());
        return (int)result;
    }
}


