package org.vetcontrol.model.beans;
// Generated Dec 2, 2009 5:41:21 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Node generated by hbm2java
 */
@Entity
@Table(name="node"
    ,catalog="project1"
)
public class Node  implements java.io.Serializable {


     private Integer nodeId;
     private String nodeName;
     private Set<User> users = new HashSet<User>(0);

    public Node() {
    }

	
    public Node(String nodeName) {
        this.nodeName = nodeName;
    }
    public Node(String nodeName, Set<User> users) {
       this.nodeName = nodeName;
       this.users = users;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="nodeId", unique=true, nullable=false)
    public Integer getNodeId() {
        return this.nodeId;
    }
    
    public void setNodeId(Integer nodeId) {
        this.nodeId = nodeId;
    }
    
    @Column(name="nodeName", nullable=false, length=45)
    public String getNodeName() {
        return this.nodeName;
    }
    
    public void setNodeName(String nodeName) {
        this.nodeName = nodeName;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="node")
    public Set<User> getUsers() {
        return this.users;
    }
    
    public void setUsers(Set<User> users) {
        this.users = users;
    }




}


