package org.vetcontrol.model.beans;
// Generated Dec 2, 2009 5:41:21 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name = "role", catalog = "project1")
public class Role implements java.io.Serializable {

    private RoleId id;
    private User user;

    public Role() {
    }

    public Role(RoleId id, User user) {
        this.id = id;
        this.user = user;
    }

    @EmbeddedId
    @AttributeOverrides({
        @AttributeOverride(name = "role", column = @Column(name = "role", nullable = false, length = 45)),
        @AttributeOverride(name = "userName", column = @Column(name = "userName", nullable = false, length = 45))})
    public RoleId getId() {
        return this.id;
    }

    public void setId(RoleId id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "userName", nullable = false, insertable = false, updatable = false)
    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }
}


