package org.vetcontrol.model.beans;
// Generated Dec 2, 2009 6:18:15 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Roles generated by hbm2java
 */
@Entity
@Table(name = "roles", catalog = "project1")
public class Roles implements java.io.Serializable {

    private String name;

    public Roles() {
    }

    public Roles(String name) {
        this.name = name;
    }

    @Id
    @Column(name = "name", unique = true, nullable = false, length = 45)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }
}


