package org.vetcontrol.model;
// Generated Dec 17, 2009 12:53:27 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Culturestring generated by hbm2java
 */
@Entity
@Table(name = "culturestring", catalog = "project1")
public class CultureString implements java.io.Serializable {

    private CultureStringId id;
    private String value;

    public CultureString() {
    }

    public CultureString(CultureStringId id) {
        this.id = id;
    }

    public CultureString(CultureStringId id, String value) {
        this.id = id;
        this.value = value;
    }

    @EmbeddedId
    @AttributeOverrides({
        @AttributeOverride(name = "stringId", column =
        @Column(name = "stringId", nullable = false)),
        @AttributeOverride(name = "locale", column =
        @Column(name = "locale", nullable = false, length = 2))})
    public CultureStringId getId() {
        return this.id;
    }

    public void setId(CultureStringId id) {
        this.id = id;
    }

    @Column(name = "value", length = 1024)
    public String getValue() {
        return this.value;
    }

    public void setValue(String value) {
        this.value = value;
    }
}


