package org.vetcontrol.entity;
// Generated Dec 17, 2009 1:05:58 PM by Hibernate Tools 3.2.1.GA

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import org.vetcontrol.util.book.entity.annotation.MappedProperty;

/**
 * Countrybook generated by hbm2java
 */
@Entity
@Table(name = "countrybook")
public class CountryBook implements java.io.Serializable {

    private Long id;
    private String code;
    private long name;
    private List<StringCulture> names = new ArrayList<StringCulture>();

    public CountryBook() {
    }

    public CountryBook(String code) {
        this.code = code;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Column(name = "code", nullable = false, length = 2)
    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    @MappedProperty("name")
    @Transient
    @Column(length = 10, nullable = false)
    public List<StringCulture> getNames() {
        return this.names;
    }

    public void setNames(List<StringCulture> names) {
        this.names = names;
    }

    public void addName(StringCulture name) {
        names.add(name);
    }

    @Column(name = "name")
    public long getName() {
        return name;
    }

    public void setName(long name) {
        this.name = name;
    }
}


