package org.vetcontrol.model.beans;
// Generated Dec 2, 2009 5:41:21 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RoleId generated by hbm2java
 */
@Embeddable
public class RoleId  implements java.io.Serializable {


     private String role;
     private String userName;

    public RoleId() {
    }

    public RoleId(String role, String userName) {
       this.role = role;
       this.userName = userName;
    }
   

    @Column(name="role", nullable=false, length=45)
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }

    @Column(name="userName", nullable=false, length=45)
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RoleId) ) return false;
		 RoleId castOther = ( RoleId ) other; 
         
		 return ( (this.getRole()==castOther.getRole()) || ( this.getRole()!=null && castOther.getRole()!=null && this.getRole().equals(castOther.getRole()) ) )
 && ( (this.getUserName()==castOther.getUserName()) || ( this.getUserName()!=null && castOther.getUserName()!=null && this.getUserName().equals(castOther.getUserName()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getRole() == null ? 0 : this.getRole().hashCode() );
         result = 37 * result + ( getUserName() == null ? 0 : this.getUserName().hashCode() );
         return result;
   }   


}


