package org.vetcontrol.model.beans;
// Generated Dec 2, 2009 5:41:21 PM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.annotations.Cascade;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "project1")
public class User implements java.io.Serializable {

    private String name;
    private Node node;
    private String login;
    private String password;
    private boolean blocked;
    private Set<Role> roles = new HashSet<Role>(0);

    public User() {
    }

    public User(String name, String password, boolean blocked) {
        this.name = name;
        this.password = password;
        this.blocked = blocked;
    }

    public User(String name, Node node, String login, String password, boolean blocked, Set<Role> roles) {
        this.name = name;
        this.node = node;
        this.login = login;
        this.password = password;
        this.blocked = blocked;
        this.roles = roles;
    }

    @Id
    @Column(name = "name", unique = true, nullable = false, length = 45)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "parentNodeId")
    public Node getNode() {
        return this.node;
    }

    public void setNode(Node node) {
        this.node = node;
    }

    @Column(name = "login", length = 45)
    public String getLogin() {
        return this.login;
    }

    public void setLogin(String login) {
        this.login = login;
    }

    @Column(name = "password", nullable = false, length = 45)
    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @Column(name = "blocked", nullable = false)
    public boolean isBlocked() {
        return this.blocked;
    }

    public void setBlocked(boolean blocked) {
        this.blocked = blocked;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER, mappedBy = "user")
    @Cascade(org.hibernate.annotations.CascadeType.DELETE_ORPHAN)
    public Set<Role> getRoles() {
        return this.roles;
    }

    public void setRoles(Set<Role> roles) {
        this.roles = roles;
    }
}


