package org.vetcontrol.information.model;
// Generated Dec 10, 2009 11:18:43 AM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Book1 generated by hbm2java
 */
@Entity
@Table(name = "book1", catalog = "project1")
public class Book1 implements java.io.Serializable {

    private Integer key1;
    private String value1;
    private String value2;
    private String value3;
    private Date dateValue;

    public Book1() {
    }

    public Book1(String value1, String value2, String value3, Date dateValue) {
        this.value1 = value1;
        this.value2 = value2;
        this.value3 = value3;
        this.dateValue = dateValue;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "key1", unique = true, nullable = false)
    public Integer getKey1() {
        return this.key1;
    }

    public void setKey1(Integer key1) {
        this.key1 = key1;
    }

    @Column(name = "value1", length = 20)
    public String getValue1() {
        return this.value1;
    }

    public void setValue1(String value1) {
        this.value1 = value1;
    }

    @Column(name = "value2", length = 20)
    public String getValue2() {
        return this.value2;
    }

    public void setValue2(String value2) {
        this.value2 = value2;
    }

    @Column(name = "value3", length = 100)
    public String getValue3() {
        return this.value3;
    }

    public void setValue3(String value3) {
        this.value3 = value3;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "dateValue", length = 10)
    public Date getDateValue() {
        return this.dateValue;
    }

    public void setDateValue(Date dateValue) {
        this.dateValue = dateValue;
    }
}


