package org.vetcontrol.information.model;
// Generated Dec 9, 2009 12:57:22 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Book2 generated by hbm2java
 */
@Entity
@Table(name="book2")
public class Book2  implements java.io.Serializable {


     private Integer key1;
     private String val1;
     private String val2;
     private String val3;
     private String val4;

    public Book2() {
    }

    public Book2(String val1, String val2, String val3, String val4) {
       this.val1 = val1;
       this.val2 = val2;
       this.val3 = val3;
       this.val4 = val4;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="key1", unique=true, nullable=false)
    public Integer getKey1() {
        return this.key1;
    }
    
    public void setKey1(Integer key1) {
        this.key1 = key1;
    }
    
    @Column(name="val1", length=20)
    public String getVal1() {
        return this.val1;
    }
    
    public void setVal1(String val1) {
        this.val1 = val1;
    }
    
    @Column(name="val2", length=50)
    public String getVal2() {
        return this.val2;
    }
    
    public void setVal2(String val2) {
        this.val2 = val2;
    }
    
    @Column(name="val3", length=50)
    public String getVal3() {
        return this.val3;
    }
    
    public void setVal3(String val3) {
        this.val3 = val3;
    }
    
    @Column(name="val4", length=100)
    public String getVal4() {
        return this.val4;
    }
    
    public void setVal4(String val4) {
        this.val4 = val4;
    }




}


