package org.vetcontrol.information.model;
// Generated Dec 21, 2009 12:17:35 PM by Hibernate Tools 3.2.1.GA

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import org.vetcontrol.information.util.model.annotation.MappedProperty;

/**
 * Registeredproducts generated by hbm2java
 */
@Entity
@Table(name = "registeredproducts")
public class Registeredproducts implements java.io.Serializable {

    private Integer id;
    private long name;
    private long classificator;
    private String vendor;
    private String country;
    private String regnumber;
    private Date date;

    public Registeredproducts() {
    }

    public Registeredproducts(String vendor, String country, String regnumber, Date date) {
        this.vendor = vendor;
        this.country = country;
        this.regnumber = regnumber;
        this.date = date;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "name", nullable = false)
    public long getName() {
        return this.name;
    }

    public void setName(long name) {
        this.name = name;
    }

    @Column(name = "classificator", nullable = false)
    public long getClassificator() {
        return this.classificator;
    }

    public void setClassificator(long classificator) {
        this.classificator = classificator;
    }

    @Column(name = "vendor", nullable = false, length = 50)
    public String getVendor() {
        return this.vendor;
    }

    public void setVendor(String vendor) {
        this.vendor = vendor;
    }

    @Column(name = "country", nullable = false, length = 2)
    public String getCountry() {
        return this.country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    @Column(name = "regnumber", nullable = false, length = 50)
    public String getRegnumber() {
        return this.regnumber;
    }

    public void setRegnumber(String regnumber) {
        this.regnumber = regnumber;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "date", nullable = false, length = 10)
    public Date getDate() {
        return this.date;
    }

    public void setDate(Date date) {
        this.date = date;
    }
    private List<StringCulture> names = new ArrayList<StringCulture>();

    /**
     * Get the value of names
     *
     * @return the value of names
     */
    @MappedProperty("name")
    @Transient
    @Column(length = 10, nullable = false)
    public List<StringCulture> getNames() {
        return names;
    }

    /**
     * Set the value of names
     *
     * @param names new value of names
     */
    public void setNames(List<StringCulture> names) {
        this.names = names;
    }

    public void addName(StringCulture name) {
        names.add(name);
    }
    private List<StringCulture> classificators = new ArrayList<StringCulture>();

    /**
     * Get the value of classificators
     *
     * @return the value of classificators
     */
    @MappedProperty("classificator")
    @Transient
    @Column(length = 10, nullable = false)
    public List<StringCulture> getClassificators() {
        return classificators;
    }

    /**
     * Set the value of classificators
     *
     * @param classificators new value of classificators
     */
    public void setClassificators(List<StringCulture> classificators) {
        this.classificators = classificators;
    }

    public void addClassificator(StringCulture classificator) {
        classificators.add(classificator);
    }
}


